[package]
name = "test-harness"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-control-plane = { path = "../rust-control-plane" }
data-plane-api = { path = "../data-plane-api" }
log = "0.4"
env_logger = "0.9"
reqwest = "0.11"
tonic = "0.8"
tokio = { version = "1", features = ["full"] }
