name: test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout recursive
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Install envoy
        run: brew install envoy
      - name: Install protoc
        run: brew install protobuf
      - name: Build
        run: cargo build
      - name: Clippy
        run: cargo clippy
      - name: Unit tests
        run: cargo test --all
      # Without delta
      - name: Integration test1
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test1
      - name: Integration test1 with ADS
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test1 --ads
      - name: Integration test2
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test2
      - name: Integration test2 with ADS
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test2 --ads
      - name: Integration test3
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test3
      - name: Integration test3 with ADS
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test3 --ads
      # With delta
      - name: Integration test1 with delta
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test1 --delta
      - name: Integration test1 with delta and ADS
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test1 --ads --delta
      - name: Integration test2 with delta
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test2 --delta
      - name: Integration test2 with delta and ADS
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test2 --ads --delta
      - name: Integration test3 with delta
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test3 --delta
      - name: Integration test3 with delta and ADS
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test3 --ads --delta
