name: test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install envoy
        run: brew install envoy
      - name: Install protoc
        run: brew install protoc
      - name: Build
        run: cargo build
      - name: Test1
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test1
