name: test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout recursive
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install envoy
        run: brew install envoy
      - name: Install protoc
        run: brew install protobuf
      - name: Build
        run: cargo build
      - name: Unit tests
        run: cargo test --all
      - name: Integration test1
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test1
      - name: Integration test2
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test2
      - name: Integration test3
        working-directory: ./test-harness
        run: RUST_LOG=info cargo run -- -n test3
